const copy = {
  zh: {library:'布局库',general:'通用',spacing:'窗口与布局',screen:'当前屏幕',windows:'4 个窗口待整理',all:'本屏全部窗口',one:'当前窗口',presets:'选择一个布局',available:'21 种内置布局 · 这里试试常用的六种',preview:'分配预览',apply:'体验排列',done:'示意已更新',demo:'交互界面示意，不会修改你的 Mac',language:'语言',follow:'跟随系统',startup:'登录时自动启动',settings:'让窗多多按你的习惯工作。',spaceIntro:'一点空隙，让内容更从容。',gap:'窗口间距',margin:'屏幕边距',drag:'拖拽贴边吸附',example:'间距预览',reset:'恢复默认',version:'v0.3.6 Beta · 构建 26',labels:['左右平分','三列','四宫格','六分区','九分区','十二分区'],apps:['浏览器','编辑器','笔记','终端'],current:'当前窗口',system:'本地处理 · 无需账号'},
  en: {library:'Layout library',general:'General',spacing:'Windows & spacing',screen:'Current display',windows:'4 windows to arrange',all:'All windows',one:'Current window',presets:'Choose a layout',available:'21 built-in layouts · Try six favorites here',preview:'Assignment preview',apply:'Try arranging',done:'Preview updated',demo:'Interactive illustration. Your Mac stays unchanged.',language:'Language',follow:'Follow system',startup:'Open at login',settings:'Make SnapTiler work your way.',spaceIntro:'A little space. A clearer view.',gap:'Window gap',margin:'Screen margin',drag:'Snap when dragging to an edge',example:'Spacing preview',reset:'Reset',version:'v0.3.6 Beta · Build 26',labels:['Halves','Three columns','Four-up','Six zones','Nine zones','Twelve zones'],apps:['Browser','Editor','Notes','Terminal'],current:'Current window',system:'On your Mac · No account needed'}
};
export function initProductPreview() {
  const host=document.getElementById('product-preview');
  if(!host)return;
  let mode='layout-library',zones=4,all=true,gap=8,margin=8,startup=true,drag=true,language='system',arranged=false;
  const counts=[2,3,4,6,9,12],cols=n=>n===2?2:n===3?3:n===4?2:n===6?3:n===9?3:4;
  const text=()=>copy[document.documentElement.lang==='en'?'en':'zh'];
  const icon=name=>`<img src="./assets/icons/${name}.svg" alt="" width="18" height="18">`;
  const miniature=n=>`<span class="ui-mini" style="--columns:${cols(n)}">${Array.from({length:n},()=>'<i></i>').join('')}</span>`;
  function render(){
    const c=text(),en=document.documentElement.lang==='en',title=mode==='layout-library'?c.library:mode==='settings-general'?c.general:c.spacing;
    host.innerHTML=`<div class="ui-window"><div class="ui-titlebar"><span class="ui-lights" aria-hidden="true"><i></i><i></i><i></i></span><span>${title}</span><span class="ui-version">${c.version}</span></div><div class="ui-shell ${mode==='layout-library'?'is-library':''}">${mode!=='layout-library'?`<aside class="ui-sidebar"><nav aria-label="${en?'Preview navigation':'示意界面导航'}">${[['settings-general','command',c.general],['settings-layouts','grid-four',c.spacing],['layout-library','squares-four',c.library]].map(([key,i,label])=>`<button type="button" data-preview-mode="${key}" aria-current="${key===mode?'page':'false'}">${icon(i)}<span>${label}</span></button>`).join('')}</nav><p class="ui-local">${icon('shield-check')}<span>${c.system}</span></p></aside>`:''}<div class="ui-content">${mode==='layout-library'?library(c):mode==='settings-general'?general(c):spacing(c)}</div></div><div class="ui-bottom-note">${icon('cursor')}<span>${c.demo}</span></div></div>`;
    for(const b of document.querySelectorAll('[data-product]'))b.setAttribute('aria-pressed',String(b.dataset.product===mode));
  }
  function library(c){return `<div class="ui-screen"><div>${icon('monitor')}<span><strong>${c.screen}</strong><small>${c.windows}</small></span></div><div class="ui-segment"><button type="button" data-preview-target="all" aria-pressed="${all}">${c.all}</button><button type="button" data-preview-target="one" aria-pressed="${!all}">${c.one}</button></div></div><div class="ui-library"><div><h3>${c.presets}</h3><p class="ui-helper">${c.available}</p><div class="ui-layout-list">${counts.map((n,i)=>`<button type="button" class="ui-layout-choice" data-preview-layout="${n}" aria-pressed="${n===zones}">${miniature(n)}<span>${c.labels[i]}</span></button>`).join('')}</div></div><div class="ui-assignment"><div class="ui-preview-heading"><span>${c.preview}</span><strong>${c.labels[counts.indexOf(zones)]}</strong></div><div class="ui-zones ${arranged?'is-arranged':''}" style="--columns:${cols(zones)}">${Array.from({length:zones},(_,i)=>`<span class="${i<(all?4:1)?'occupied':''}">${i<(all?4:1)?`<b>${String(i+1).padStart(2,'0')}</b><small>${all?c.apps[i]:c.current}</small>`:''}</span>`).join('')}</div><button type="button" class="ui-primary" data-preview-apply>${arranged?c.done:c.apply}${icon(arranged?'check':'arrow-right')}</button></div></div>`;}
  function general(c){return `<div class="ui-heading"><h3>${c.general}</h3><p>${c.settings}</p></div><div class="ui-settings-group"><label class="ui-setting"><span>${c.language}</span><select data-preview-language aria-label="${c.language}"><option value="system" ${language==='system'?'selected':''}>${c.follow}</option><option value="zh" ${language==='zh'?'selected':''}>简体中文</option><option value="en" ${language==='en'?'selected':''}>English</option></select></label><div class="ui-setting"><span>${c.startup}</span><button type="button" class="ui-switch" role="switch" aria-checked="${startup}" aria-label="${c.startup}" data-preview-toggle="startup"><i></i></button></div></div><div class="ui-general-feature">${icon('squares-four')}<h4>${c.library}</h4><p>${c.available}</p><button type="button" class="ui-link" data-preview-mode="layout-library">${c.presets} ${icon('arrow-right')}</button></div>`;}
  function spacing(c){return `<div class="ui-heading"><h3>${c.spacing}</h3><p>${c.spaceIntro}</p></div><div class="ui-settings-group">${[['margin',c.margin,margin],['gap',c.gap,gap]].map(([key,label,val])=>`<label class="ui-slider"><span>${label}<output data-value="${key}">${val} pt</output></span><input type="range" data-preview-range="${key}" min="0" max="32" value="${val}" aria-label="${label}"></label>`).join('')}</div><div class="ui-spacing-board" style="gap:${gap}px;padding:${margin}px" aria-label="${c.example}">${c.apps.map(a=>`<div><span class="ui-mini-title">${a}</span><i></i><i></i><i></i></div>`).join('')}</div><div class="ui-setting ui-drag-setting"><span>${c.drag}</span><button type="button" class="ui-switch" role="switch" aria-checked="${drag}" aria-label="${c.drag}" data-preview-toggle="drag"><i></i></button><button type="button" class="ui-reset" data-preview-reset>${c.reset}</button></div>`;}
  for(const button of document.querySelectorAll('[data-product]'))button.addEventListener('click',()=>{mode=button.dataset.product;render();});
  host.addEventListener('click',event=>{
    const b=event.target.closest('button');if(!b)return;
    if(b.dataset.previewMode){mode=b.dataset.previewMode;render();}
    else if(b.dataset.previewLayout){zones=Number(b.dataset.previewLayout);arranged=false;render();}
    else if(b.dataset.previewTarget){all=b.dataset.previewTarget==='all';arranged=false;render();}
    else if(b.hasAttribute('data-preview-apply')){arranged=true;b.textContent=text().done;host.querySelector('.ui-zones').classList.add('is-arranged');}
    else if(b.dataset.previewToggle){if(b.dataset.previewToggle==='startup')startup=!startup;else drag=!drag;b.setAttribute('aria-checked',String(b.dataset.previewToggle==='startup'?startup:drag));}
    else if(b.hasAttribute('data-preview-reset')){gap=8;margin=8;drag=true;render();}
  });
  host.addEventListener('input',event=>{const key=event.target.dataset.previewRange;if(!key)return;const value=Number(event.target.value);if(key==='gap')gap=value;else margin=value;host.querySelector(`[data-value="${key}"]`).textContent=`${value} pt`;const board=host.querySelector('.ui-spacing-board');board.style.gap=`${gap}px`;board.style.padding=`${margin}px`;});
  host.addEventListener('change',event=>{if(event.target.hasAttribute('data-preview-language'))language=event.target.value;});
  document.addEventListener('site-language',render);
  render();
}
